### PR TITLE
Used NumPy to make things speedy

### PR DESCRIPTION
**Pull request by ben-eysenbach**
Comparison of performance before and after:
speedup

The numpy version is faster with matrices larger than 13x13:
speedup2

### CODE REVIEW

**Comment by bmc** [comment]
Sorry, I never got to this. It's no longer mergeable as is. If it's still of interest, please fix, verify that it passes tests, and I'll merge.

**Comment by anthrotype** [comment]
@bmc I'd suggest to keep munkres a pure-python package without dependencies on C extension modules like numpy. Or at least, making numpy an extra dependency, not required.
For me, the biggest selling point of this package is that it does *not* require numpy (which of course makes it slower, but also more portable and easier to install). If one wants a numpy-powered implementation of the munkres algorithm, one can already use [scipy.optimize.linear_sum_assignment](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.linear_sum_assignment.html).

**Comment by bmc** [comment]
I can buy that logic.

**Comment by wattse** [comment]
@anthrotype and @bmc, one argument to provide a numpy back-end for this algorithm is that scipy's algorithm doesn't permit disallowed assignments, which is why I've grabbed this version.

**Pull request closed without merging**
